### ISSUE TITLE
Different approach in reactions generating

### ISSUE THREAD

**Issue by mathooo** [sybila/BCSgen#35]
Currently, new method for generating reactions is applied and then the state space is generated with them. However, this method is not the fastest one and maybe the faster method (used in Biocham) should be used.

* _generating reaction network_  - use our new method since we want accurate reaction network (i.e. static analysis is also applied)
* _generating state space_ - use Biocham method to achieve faster results (however, reactions are not produced as by-product)

---

__Biocham method__

Generates all combinations of agents in rules and produces all possible reactions.

* detect all possible instances of agents (This could be used also in SBML export),
* create combinations (not that easy, pairs from left and right-hand-side must be matched first).

**Comment by mathooo** [comment]
Just to think - once we apply this method, the semantics of BCSL will vanish at all. It means, the semantics won't be actually used in state space generating what follows indirect semantics.

**Comment by mathooo** [comment]
BNGL inspiration - [manual](http://bionetgen.org/index.php/BNGManual:Generating_a_Network), [paper](http://link.springer.com/chapter/10.1007%2F11905455_5)

**Comment by mathooo** [comment]
``>>> dictT = { 'kaic' : { 'S' : ['u', 'p'], 'T' : ['u', 'p']}, 'KaiB' : {} }``
``>>> dictT``
``{'kaic': {'S': ['u', 'p'], 'T': ['u', 'p']}, 'KaiB': {}}``
``>>> dictT['kaic']``
``{'S': ['u', 'p'], 'T': ['u', 'p']}``
``>>> dictT['kaic']['S']``
``['u', 'p']``
``>>> dictT['kaic']['S'][0]``
``'u'``
``>>> dictT['kaic']['S'][1]``
``'p'``
``>>> dictT['A']``
``Traceback (most recent call last):``
``  File "<stdin>", line 1, in <module>``
``KeyError: 'A'``
``>>> dictT['A'] = {}``
``>>> dictT``
``{'A': {}, 'kaic': {'S': ['u', 'p'], 'T': ['u', 'p']}, 'KaiB': {}}``
``>>> dictT['A'] = {'X' : ['i']}``
``>>> dictT``
``{'A': {'X': ['i']}, 'kaic': {'S': ['u', 'p'], 'T': ['u', 'p']}, 'KaiB': {}}``
``>>> dictT['A'] = {'Y' : ['i']}``
``>>> dictT``
``{'A': {'Y': ['i']}, 'kaic': {'S': ['u', 'p'], 'T': ['u', 'p']}, 'KaiB': {}}``
``>>> dictT['A'] += {'Y' : ['i']}``
``Traceback (most recent call last):``
``  File "<stdin>", line 1, in <module>``
``TypeError: unsupported operand type(s) for +=: 'dict' and 'dict'``
``>>> dictT['A'].update({'X' : ['i']})``
``>>> dictT``
``{'A': {'Y': ['i'], 'X': ['i']}, 'kaic': {'S': ['u', 'p'], 'T': ['u', 'p']}, 'KaiB': {}}``
``>>> dictT['A']['X'].append('a')``
``>>> dictT``
``{'A': {'Y': ['i'], 'X': ['i', 'a']}, 'kaic': {'S': ['u', 'p'], 'T': ['u', 'p']}, 'KaiB': {}}``
